### ISSUE TITLE
Autoriseerimine

### ISSUE THREAD

**Issue by toivoalp** [lauri0/LST#17]

**Comment by lauri0** [comment]
Soovitamise (ehk hetkel sisuliselt kommentaari lisamise) leht on piiratud ligipääsuga. Kui kasutaja üritab sellele lehele minna, ilma et ta oleks Google kaudu sisse logitud nõutakse temalt esmalt selle tegemist. Pole vahet, kas kasutaja üritab kommentaari lisamise lehele ligi pääseda urli sisestamise või "Soovita" nupule vajutamise kaudu.
