### ISSUE TITLE
Meldimise (i.k. log in) järel näidatakse lehte, millele kasutaja soovis minna   (st. millele viidati)  

### ISSUE THREAD

**Issue by toivoalp** [lauri0/LST#18]

**Comment by lauri0** [comment]
Kui kasutaja pole sisse logitud ning klikkab "Soovita" nupul, lastakse kasutajal esmalt sisse logida ning siis viiakse ta edasi soovitamise lehele. Kui kasutaja logib sisse olles mingil muul lehel, viiakse ta pärast autentimist tagasi eelnevale lehele. Sama toimib ka välja logimisega.
