### ISSUE TITLE
Andmebaasi suhtlus Heroku serveris

### ISSUE THREAD

**Issue by toivoalp** [lauri0/LST#25]

**Comment by siiri1307** [comment]
Andmebaasist info saamise testimiseks sisestada otsinguribale nimi "Mari Maasik" või "Oskar Mets". Seejärel avaneb leht nende inimeste poliitiliste soovituste ja kommentaariga. Leheküljelt https://nameless-hollows-9873.herokuapp.com/soovitajate-nimekiri näeb soovitajate nimekirja perekonnanime tähestikulises järjekorras. Leheküljelt https://nameless-hollows-9873.herokuapp.com/statistika näeb statistikat, mitu inimest on oma soovituse jätnud, mis on realiseeritud, kasutades GROUP BY lauset. Leheküljelt https://nameless-hollows-9873.herokuapp.com/comment saab sisestada oma elukutse ja kommentaari, mis salvestatakse andmebaasi. See on hetkel realiseeritud soovitaja isendi sisse kirjutamisega klassi CommentServlet. Töötame selle kallal, et ühendada see lehekülg sisse logimise leheküljega ja isku tuvastamisega.
